
version: 2.1
jobs:
  build:
    machine: true
    steps:
      ## install more recent version of docker-compose
      - run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-compose
      ##  old way of installing docker-compose
      #- run: |
      #   sudo DEBIAN_FRONTEND=noninteractive apt-get update
      #   sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev libssl-dev python3-dev python3-pyqt5 python3-pyqt5.qtwebengine python3 python3-pip
      #- run: pip3 install docker-compose
      - run: sudo usermod -aG docker $USER
      ## build base container (multistage build)
      - checkout
      - run: |
          echo "UID=$(id -u)" > ./docker/.env
          echo "GID=$(id -g)" >> ./docker/.env
          cd ./docker
          docker-compose build --no-cache
          docker-compose -f ./docker-compose.yml run --rm linux-develop
