
version: 2.1
jobs:
  build:
    machine: true
    steps:
      ## install more recent version of docker-compose
      - run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-compose
      - run: sudo usermod -aG docker $USER
      ## build base container (multistage build)
      - checkout
      - run: |
          echo "UID=$(id -u)" > ./docker/.env
          echo "GID=$(id -g)" >> ./docker/.env
          cd ./docker
          docker-compose build --no-cache
          ## active (takes time)
          #docker-compose -f ./docker-compose.yml run --rm linux-develop
          ## passive/dry-run
          docker-compose -f ./docker-compose.yml run --rm linux-develop /usr/bin/date
