version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout

     # buildroot
     - run: cd ./docker && time docker build --no-cache --build-arg USER=$USER --build-arg GMAIL_USER="Erika Mustermann" --build-arg GMAIL=erika_mustermann@gmail.com --build-arg GMAIL_PASSW=password -t rubuschl/linuxpatches:123 .
     - run: cd ./docker && docker run --rm -ti --user=$USER:$USER --workdir=/home/$USER -v $PWD/configs:/home/$USER/configs -v $PWD/linux:/home/$USER/linux rubuschl/linuxpatches:123
