version: 2.1
jobs:
  build:
    machine: true
    steps:
      ## install more recent version of docker-compose
      - run: |
         sudo DEBIAN_FRONTEND=noninteractive apt-get update
         sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev libssl-de
      - run: pip3 install docker-compose
      - run: sudo usermod -aG docker $USER
      ## build base container (multistage build)
      - checkout
      - run: |
          cd ./docker
          docker-compose up --exit-code-from linux
