version: '3.8'

services:
    devel-rpi-arm32:
        container_name: devel-rpi-arm32
        image: ${USER}/devel-rpi-arm32
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"   ## docker run --user=$USER
        stdin_open: true        ## docker run -i
        tty: true               ## docker run -t
        privileged: true
        environment:
          - USER
        env_file:
          - .env
        volumes:
        ## folders not need to be around
        #  - ~/.gitconfig:/home/${USER}/.gitconfig
        # - ~/.ssh:/home/${USER}/.ssh
          - ./workspace:/home/$USER/workspace
        ## folder must be around
          - type: bind
            source: ~/.ssh
            target: /home/${USER}/.ssh
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
